return {
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. They are made of leather, gauze, and wicked intent.\\n\\n<i>Become notorious</i>",
      id = "skin-fb30d56f4210_4",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/leather_handwraps_handwrap_leathery_heavy_png.png",
      legacy_model = false,
      market_hash_name = "★ Hand Wraps | Leather (Battle-Scarred)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Hand Wraps | Leather (Battle-Scarred)",
      paint_index = "10009",
      pattern = {
        id = "handwrap_leathery",
        name = "Leather"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-fb30d56f4210",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "leather_handwraps",
        name = "Hand Wraps",
        weapon_id = 5032
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_4",
        name = "Battle-Scarred"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
      id = "skin-be5a5c9a12c2_0",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/leather_handwraps_handwrap_leathery_snakeskin_orange_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Hand Wraps | Constrictor (Factory New)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Hand Wraps | Constrictor (Factory New)",
      paint_index = "10083",
      pattern = {
        id = "handwrap_leathery_snakeskin_orange",
        name = "Constrictor"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-be5a5c9a12c2",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "leather_handwraps",
        name = "Hand Wraps",
        weapon_id = 5032
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_0",
        name = "Factory New"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
      id = "skin-be5a5c9a12c2_1",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/leather_handwraps_handwrap_leathery_snakeskin_orange_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Hand Wraps | Constrictor (Minimal Wear)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Hand Wraps | Constrictor (Minimal Wear)",
      paint_index = "10083",
      pattern = {
        id = "handwrap_leathery_snakeskin_orange",
        name = "Constrictor"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-be5a5c9a12c2",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "leather_handwraps",
        name = "Hand Wraps",
        weapon_id = 5032
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_1",
        name = "Minimal Wear"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
      id = "skin-be5a5c9a12c2_2",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/leather_handwraps_handwrap_leathery_snakeskin_orange_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Hand Wraps | Constrictor (Field-Tested)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Hand Wraps | Constrictor (Field-Tested)",
      paint_index = "10083",
      pattern = {
        id = "handwrap_leathery_snakeskin_orange",
        name = "Constrictor"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-be5a5c9a12c2",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "leather_handwraps",
        name = "Hand Wraps",
        weapon_id = 5032
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_2",
        name = "Field-Tested"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
      id = "skin-be5a5c9a12c2_3",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/leather_handwraps_handwrap_leathery_snakeskin_orange_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Hand Wraps | Constrictor (Well-Worn)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Hand Wraps | Constrictor (Well-Worn)",
      paint_index = "10083",
      pattern = {
        id = "handwrap_leathery_snakeskin_orange",
        name = "Constrictor"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-be5a5c9a12c2",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "leather_handwraps",
        name = "Hand Wraps",
        weapon_id = 5032
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_3",
        name = "Well-Worn"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching.",
      id = "skin-be5a5c9a12c2_4",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/leather_handwraps_handwrap_leathery_snakeskin_orange_heavy_png.png",
      legacy_model = false,
      market_hash_name = "★ Hand Wraps | Constrictor (Battle-Scarred)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Hand Wraps | Constrictor (Battle-Scarred)",
      paint_index = "10083",
      pattern = {
        id = "handwrap_leathery_snakeskin_orange",
        name = "Constrictor"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-be5a5c9a12c2",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "leather_handwraps",
        name = "Hand Wraps",
        weapon_id = 5032
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_4",
        name = "Battle-Scarred"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. Dyed crimson, these wraps make it hard to see where the fabric ends and the bloodstains begin\\n\\n<i>Who doesn't love working with their hands?</i>",
      id = "skin-1f6ac4772c2b_0",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/leather_handwraps_handwrap_red_slaughter_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Hand Wraps | Slaughter (Factory New)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Hand Wraps | Slaughter (Factory New)",
      paint_index = "10021",
      pattern = {
        id = "handwrap_red_slaughter",
        name = "Slaughter"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-1f6ac4772c2b",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "leather_handwraps",
        name = "Hand Wraps",
        weapon_id = 5032
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_0",
        name = "Factory New"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. Dyed crimson, these wraps make it hard to see where the fabric ends and the bloodstains begin\\n\\n<i>Who doesn't love working with their hands?</i>",
      id = "skin-1f6ac4772c2b_1",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/leather_handwraps_handwrap_red_slaughter_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Hand Wraps | Slaughter (Minimal Wear)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Hand Wraps | Slaughter (Minimal Wear)",
      paint_index = "10021",
      pattern = {
        id = "handwrap_red_slaughter",
        name = "Slaughter"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-1f6ac4772c2b",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "leather_handwraps",
        name = "Hand Wraps",
        weapon_id = 5032
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_1",
        name = "Minimal Wear"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. Dyed crimson, these wraps make it hard to see where the fabric ends and the bloodstains begin\\n\\n<i>Who doesn't love working with their hands?</i>",
      id = "skin-1f6ac4772c2b_2",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/leather_handwraps_handwrap_red_slaughter_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Hand Wraps | Slaughter (Field-Tested)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Hand Wraps | Slaughter (Field-Tested)",
      paint_index = "10021",
      pattern = {
        id = "handwrap_red_slaughter",
        name = "Slaughter"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-1f6ac4772c2b",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "leather_handwraps",
        name = "Hand Wraps",
        weapon_id = 5032
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_2",
        name = "Field-Tested"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. Dyed crimson, these wraps make it hard to see where the fabric ends and the bloodstains begin\\n\\n<i>Who doesn't love working with their hands?</i>",
      id = "skin-1f6ac4772c2b_3",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/leather_handwraps_handwrap_red_slaughter_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Hand Wraps | Slaughter (Well-Worn)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Hand Wraps | Slaughter (Well-Worn)",
      paint_index = "10021",
      pattern = {
        id = "handwrap_red_slaughter",
        name = "Slaughter"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-1f6ac4772c2b",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "leather_handwraps",
        name = "Hand Wraps",
        weapon_id = 5032
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_3",
        name = "Well-Worn"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "Preferred by hand-to-hand fighters, these wraps protect the knuckles and stabilize the wrist when punching. Dyed crimson, these wraps make it hard to see where the fabric ends and the bloodstains begin\\n\\n<i>Who doesn't love working with their hands?</i>",
      id = "skin-1f6ac4772c2b_4",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/leather_handwraps_handwrap_red_slaughter_heavy_png.png",
      legacy_model = false,
      market_hash_name = "★ Hand Wraps | Slaughter (Battle-Scarred)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Hand Wraps | Slaughter (Battle-Scarred)",
      paint_index = "10021",
      pattern = {
        id = "handwrap_red_slaughter",
        name = "Slaughter"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-1f6ac4772c2b",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "leather_handwraps",
        name = "Hand Wraps",
        weapon_id = 5032
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_4",
        name = "Battle-Scarred"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This is the original classic black design that made Tortue a household name.\\n\\n<i>Don't call it a midlife crisis</i>",
      id = "skin-d8671b33d6d9_0",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_basic_black_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Eclipse (Factory New)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Eclipse (Factory New)",
      paint_index = "10024",
      pattern = {
        id = "motorcycle_basic_black",
        name = "Eclipse"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-d8671b33d6d9",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_0",
        name = "Factory New"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This is the original classic black design that made Tortue a household name.\\n\\n<i>Don't call it a midlife crisis</i>",
      id = "skin-d8671b33d6d9_1",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_basic_black_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Eclipse (Minimal Wear)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Eclipse (Minimal Wear)",
      paint_index = "10024",
      pattern = {
        id = "motorcycle_basic_black",
        name = "Eclipse"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-d8671b33d6d9",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_1",
        name = "Minimal Wear"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This is the original classic black design that made Tortue a household name.\\n\\n<i>Don't call it a midlife crisis</i>",
      id = "skin-d8671b33d6d9_2",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_basic_black_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Eclipse (Field-Tested)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Eclipse (Field-Tested)",
      paint_index = "10024",
      pattern = {
        id = "motorcycle_basic_black",
        name = "Eclipse"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-d8671b33d6d9",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_2",
        name = "Field-Tested"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This is the original classic black design that made Tortue a household name.\\n\\n<i>Don't call it a midlife crisis</i>",
      id = "skin-d8671b33d6d9_3",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_basic_black_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Eclipse (Well-Worn)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Eclipse (Well-Worn)",
      paint_index = "10024",
      pattern = {
        id = "motorcycle_basic_black",
        name = "Eclipse"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-d8671b33d6d9",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_3",
        name = "Well-Worn"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This is the original classic black design that made Tortue a household name.\\n\\n<i>Don't call it a midlife crisis</i>",
      id = "skin-d8671b33d6d9_4",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_basic_black_heavy_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Eclipse (Battle-Scarred)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Eclipse (Battle-Scarred)",
      paint_index = "10024",
      pattern = {
        id = "motorcycle_basic_black",
        name = "Eclipse"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-d8671b33d6d9",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_4",
        name = "Battle-Scarred"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This green and grey pair has bright orange accents.",
      id = "skin-6bd9ed91c37e_0",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_basic_green_orange_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Turtle (Factory New)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Turtle (Factory New)",
      paint_index = "10050",
      pattern = {
        id = "motorcycle_basic_green_orange",
        name = "Turtle"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-6bd9ed91c37e",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_0",
        name = "Factory New"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This green and grey pair has bright orange accents.",
      id = "skin-6bd9ed91c37e_1",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_basic_green_orange_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Turtle (Minimal Wear)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Turtle (Minimal Wear)",
      paint_index = "10050",
      pattern = {
        id = "motorcycle_basic_green_orange",
        name = "Turtle"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-6bd9ed91c37e",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_1",
        name = "Minimal Wear"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This green and grey pair has bright orange accents.",
      id = "skin-6bd9ed91c37e_2",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_basic_green_orange_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Turtle (Field-Tested)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Turtle (Field-Tested)",
      paint_index = "10050",
      pattern = {
        id = "motorcycle_basic_green_orange",
        name = "Turtle"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-6bd9ed91c37e",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_2",
        name = "Field-Tested"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This green and grey pair has bright orange accents.",
      id = "skin-6bd9ed91c37e_3",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_basic_green_orange_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Turtle (Well-Worn)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Turtle (Well-Worn)",
      paint_index = "10050",
      pattern = {
        id = "motorcycle_basic_green_orange",
        name = "Turtle"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-6bd9ed91c37e",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_3",
        name = "Well-Worn"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This green and grey pair has bright orange accents.",
      id = "skin-6bd9ed91c37e_4",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_basic_green_orange_heavy_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Turtle (Battle-Scarred)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Turtle (Battle-Scarred)",
      paint_index = "10050",
      pattern = {
        id = "motorcycle_basic_green_orange",
        name = "Turtle"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-6bd9ed91c37e",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_4",
        name = "Battle-Scarred"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
      id = "skin-38236b83de3c_0",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_carbonfiber_red_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Blood Pressure (Factory New)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Blood Pressure (Factory New)",
      paint_index = "10079",
      pattern = {
        id = "motorcycle_carbonfiber_red",
        name = "Blood Pressure"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-38236b83de3c",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_0",
        name = "Factory New"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
      id = "skin-38236b83de3c_1",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_carbonfiber_red_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Blood Pressure (Minimal Wear)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Blood Pressure (Minimal Wear)",
      paint_index = "10079",
      pattern = {
        id = "motorcycle_carbonfiber_red",
        name = "Blood Pressure"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-38236b83de3c",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_1",
        name = "Minimal Wear"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
      id = "skin-38236b83de3c_2",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_carbonfiber_red_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Blood Pressure (Field-Tested)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Blood Pressure (Field-Tested)",
      paint_index = "10079",
      pattern = {
        id = "motorcycle_carbonfiber_red",
        name = "Blood Pressure"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-38236b83de3c",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_2",
        name = "Field-Tested"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
      id = "skin-38236b83de3c_3",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_carbonfiber_red_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Blood Pressure (Well-Worn)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Blood Pressure (Well-Worn)",
      paint_index = "10079",
      pattern = {
        id = "motorcycle_carbonfiber_red",
        name = "Blood Pressure"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-38236b83de3c",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_3",
        name = "Well-Worn"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
      id = "skin-38236b83de3c_4",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_carbonfiber_red_heavy_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Blood Pressure (Battle-Scarred)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Blood Pressure (Battle-Scarred)",
      paint_index = "10079",
      pattern = {
        id = "motorcycle_carbonfiber_red",
        name = "Blood Pressure"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-38236b83de3c",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_4",
        name = "Battle-Scarred"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
      id = "skin-a35568f027a4_0",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_checker_flag_blue_green_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Finish Line (Factory New)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Finish Line (Factory New)",
      paint_index = "10077",
      pattern = {
        id = "motorcycle_checker_flag_blue_green",
        name = "Finish Line"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-a35568f027a4",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_0",
        name = "Factory New"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
      id = "skin-a35568f027a4_1",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_checker_flag_blue_green_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Finish Line (Minimal Wear)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Finish Line (Minimal Wear)",
      paint_index = "10077",
      pattern = {
        id = "motorcycle_checker_flag_blue_green",
        name = "Finish Line"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-a35568f027a4",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_1",
        name = "Minimal Wear"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
      id = "skin-a35568f027a4_2",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_checker_flag_blue_green_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Finish Line (Field-Tested)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Finish Line (Field-Tested)",
      paint_index = "10077",
      pattern = {
        id = "motorcycle_checker_flag_blue_green",
        name = "Finish Line"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-a35568f027a4",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_2",
        name = "Field-Tested"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
      id = "skin-a35568f027a4_3",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_checker_flag_blue_green_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Finish Line (Well-Worn)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Finish Line (Well-Worn)",
      paint_index = "10077",
      pattern = {
        id = "motorcycle_checker_flag_blue_green",
        name = "Finish Line"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-a35568f027a4",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_3",
        name = "Well-Worn"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
      id = "skin-a35568f027a4_4",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_checker_flag_blue_green_heavy_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Finish Line (Battle-Scarred)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Finish Line (Battle-Scarred)",
      paint_index = "10077",
      pattern = {
        id = "motorcycle_checker_flag_blue_green",
        name = "Finish Line"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-a35568f027a4",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_4",
        name = "Battle-Scarred"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in brightly colored comic book onomatopoeia.",
      id = "skin-509033032197_0",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_choco_boom_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | POW! (Factory New)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | POW! (Factory New)",
      paint_index = "10049",
      pattern = {
        id = "motorcycle_choco_boom",
        name = "POW!"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-509033032197",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_0",
        name = "Factory New"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in brightly colored comic book onomatopoeia.",
      id = "skin-509033032197_1",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_choco_boom_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | POW! (Minimal Wear)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | POW! (Minimal Wear)",
      paint_index = "10049",
      pattern = {
        id = "motorcycle_choco_boom",
        name = "POW!"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-509033032197",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_1",
        name = "Minimal Wear"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in brightly colored comic book onomatopoeia.",
      id = "skin-509033032197_2",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_choco_boom_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | POW! (Field-Tested)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | POW! (Field-Tested)",
      paint_index = "10049",
      pattern = {
        id = "motorcycle_choco_boom",
        name = "POW!"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-509033032197",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_2",
        name = "Field-Tested"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in brightly colored comic book onomatopoeia.",
      id = "skin-509033032197_3",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_choco_boom_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | POW! (Well-Worn)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | POW! (Well-Worn)",
      paint_index = "10049",
      pattern = {
        id = "motorcycle_choco_boom",
        name = "POW!"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-509033032197",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_3",
        name = "Well-Worn"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in brightly colored comic book onomatopoeia.",
      id = "skin-509033032197_4",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_choco_boom_heavy_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | POW! (Battle-Scarred)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | POW! (Battle-Scarred)",
      paint_index = "10049",
      pattern = {
        id = "motorcycle_choco_boom",
        name = "POW!"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-509033032197",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_4",
        name = "Battle-Scarred"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
      id = "skin-5cbc5bc584a3_0",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_commando_ksk_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | 3rd Commando Company (Factory New)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | 3rd Commando Company (Factory New)",
      paint_index = "10080",
      pattern = {
        id = "motorcycle_commando_ksk",
        name = "3rd Commando Company"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-5cbc5bc584a3",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_0",
        name = "Factory New"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
      id = "skin-5cbc5bc584a3_1",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_commando_ksk_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | 3rd Commando Company (Minimal Wear)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | 3rd Commando Company (Minimal Wear)",
      paint_index = "10080",
      pattern = {
        id = "motorcycle_commando_ksk",
        name = "3rd Commando Company"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-5cbc5bc584a3",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_1",
        name = "Minimal Wear"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
      id = "skin-5cbc5bc584a3_2",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_commando_ksk_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | 3rd Commando Company (Field-Tested)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | 3rd Commando Company (Field-Tested)",
      paint_index = "10080",
      pattern = {
        id = "motorcycle_commando_ksk",
        name = "3rd Commando Company"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-5cbc5bc584a3",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_2",
        name = "Field-Tested"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
      id = "skin-5cbc5bc584a3_3",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_commando_ksk_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | 3rd Commando Company (Well-Worn)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | 3rd Commando Company (Well-Worn)",
      paint_index = "10080",
      pattern = {
        id = "motorcycle_commando_ksk",
        name = "3rd Commando Company"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-5cbc5bc584a3",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_3",
        name = "Well-Worn"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph.",
      id = "skin-5cbc5bc584a3_4",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_commando_ksk_heavy_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | 3rd Commando Company (Battle-Scarred)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | 3rd Commando Company (Battle-Scarred)",
      paint_index = "10080",
      pattern = {
        id = "motorcycle_commando_ksk",
        name = "3rd Commando Company"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-5cbc5bc584a3",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_4",
        name = "Battle-Scarred"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. White leather and red stitching make these gloves as stylish as they are comfortable.\\n\\n<i>For what he's charging us, you'd think Huxley could at least throw in a tin of mints... - Felix Riley, Commanding Officer</i>",
      id = "skin-a363d8de9765_0",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_mint_triangle_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Spearmint (Factory New)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Spearmint (Factory New)",
      paint_index = "10026",
      pattern = {
        id = "motorcycle_mint_triangle",
        name = "Spearmint"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-a363d8de9765",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_0",
        name = "Factory New"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. White leather and red stitching make these gloves as stylish as they are comfortable.\\n\\n<i>For what he's charging us, you'd think Huxley could at least throw in a tin of mints... - Felix Riley, Commanding Officer</i>",
      id = "skin-a363d8de9765_1",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_mint_triangle_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Spearmint (Minimal Wear)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Spearmint (Minimal Wear)",
      paint_index = "10026",
      pattern = {
        id = "motorcycle_mint_triangle",
        name = "Spearmint"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-a363d8de9765",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_1",
        name = "Minimal Wear"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. White leather and red stitching make these gloves as stylish as they are comfortable.\\n\\n<i>For what he's charging us, you'd think Huxley could at least throw in a tin of mints... - Felix Riley, Commanding Officer</i>",
      id = "skin-a363d8de9765_2",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_mint_triangle_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Spearmint (Field-Tested)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Spearmint (Field-Tested)",
      paint_index = "10026",
      pattern = {
        id = "motorcycle_mint_triangle",
        name = "Spearmint"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-a363d8de9765",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_2",
        name = "Field-Tested"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. White leather and red stitching make these gloves as stylish as they are comfortable.\\n\\n<i>For what he's charging us, you'd think Huxley could at least throw in a tin of mints... - Felix Riley, Commanding Officer</i>",
      id = "skin-a363d8de9765_3",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_mint_triangle_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Spearmint (Well-Worn)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Spearmint (Well-Worn)",
      paint_index = "10026",
      pattern = {
        id = "motorcycle_mint_triangle",
        name = "Spearmint"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-a363d8de9765",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_3",
        name = "Well-Worn"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. White leather and red stitching make these gloves as stylish as they are comfortable.\\n\\n<i>For what he's charging us, you'd think Huxley could at least throw in a tin of mints... - Felix Riley, Commanding Officer</i>",
      id = "skin-a363d8de9765_4",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_mint_triangle_heavy_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Spearmint (Battle-Scarred)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Spearmint (Battle-Scarred)",
      paint_index = "10026",
      pattern = {
        id = "motorcycle_mint_triangle",
        name = "Spearmint"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-a363d8de9765",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_4",
        name = "Battle-Scarred"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in comic book onomatopoeia.\\n\\n<i>POW! BOOM! BIFF!</i>",
      id = "skin-b3e2c06aad05_0",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_mono_boom_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Boom! (Factory New)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Boom! (Factory New)",
      paint_index = "10027",
      pattern = {
        id = "motorcycle_mono_boom",
        name = "Boom!"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-b3e2c06aad05",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_0",
        name = "Factory New"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in comic book onomatopoeia.\\n\\n<i>POW! BOOM! BIFF!</i>",
      id = "skin-b3e2c06aad05_1",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_mono_boom_light_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Boom! (Minimal Wear)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Boom! (Minimal Wear)",
      paint_index = "10027",
      pattern = {
        id = "motorcycle_mono_boom",
        name = "Boom!"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-b3e2c06aad05",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_1",
        name = "Minimal Wear"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in comic book onomatopoeia.\\n\\n<i>POW! BOOM! BIFF!</i>",
      id = "skin-b3e2c06aad05_2",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_mono_boom_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Boom! (Field-Tested)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Boom! (Field-Tested)",
      paint_index = "10027",
      pattern = {
        id = "motorcycle_mono_boom",
        name = "Boom!"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-b3e2c06aad05",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_2",
        name = "Field-Tested"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in comic book onomatopoeia.\\n\\n<i>POW! BOOM! BIFF!</i>",
      id = "skin-b3e2c06aad05_3",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_mono_boom_medium_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Boom! (Well-Worn)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Boom! (Well-Worn)",
      paint_index = "10027",
      pattern = {
        id = "motorcycle_mono_boom",
        name = "Boom!"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-b3e2c06aad05",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_3",
        name = "Well-Worn"
      }
    },
    {
      category = {
        id = "sfui_invpanel_filter_gloves",
        name = "Gloves"
      },
      description = "These bulky hard knuckled gloves can protect the wearers hands from road rash at 60 mph. This pair has been covered in comic book onomatopoeia.\\n\\n<i>POW! BOOM! BIFF!</i>",
      id = "skin-b3e2c06aad05_4",
      image = "https://raw.githubusercontent.com/ByMykel/counter-strike-image-tracker/main/static/panorama/images/econ/default_generated/motorcycle_gloves_motorcycle_mono_boom_heavy_png.png",
      legacy_model = false,
      market_hash_name = "★ Moto Gloves | Boom! (Battle-Scarred)",
      max_float = 0.8,
      min_float = 0.06,
      name = "★ Moto Gloves | Boom! (Battle-Scarred)",
      paint_index = "10027",
      pattern = {
        id = "motorcycle_mono_boom",
        name = "Boom!"
      },
      rarity = {
        color = "#eb4b4b",
        id = "rarity_ancient",
        name = "Extraordinary"
      },
      skin_id = "skin-b3e2c06aad05",
      souvenir = false,
      stattrak = false,
      style = {
        id = 0,
        name = "None"
      },
      team = {
        id = "both",
        name = "Both Teams"
      },
      weapon = {
        id = "motorcycle_gloves",
        name = "Moto Gloves",
        weapon_id = 5033
      },
      wear = {
        id = "SFUI_InvTooltip_Wear_Amount_4",
        name = "Battle-Scarred"
      }
    }
  }