[package]
name = "sigmathetatech/sigmatech-luau-project-base"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "0.1.0"

# Loader + TypedRemote will take place of Knit
[dependencies]
Janitor = "howmanysmall/janitor@1.16.0"
Loader = "sleitnick/loader@2.0.0"
Promise = "evaera/promise@4.0.0"
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
Signal = "sleitnick/signal@2.0.1"
TypedRemote = "sleitnick/typed-remote@0.3.0"
UILabs = "pepeeltoro41/ui-labs@2.4.1"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"
