[package]
name = "sigmathetatech/sigmatech-luau-project-base"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

# Loader + TypedRemote will take place of Knit
[dependencies]
Loader = "sleitnick/loader@2.0.0"
TypedRemote = "sleitnick/typed-remote@0.2.0"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.1"
Janitor = "howmanysmall/janitor@1.16.0"
Fusion = "elttob/fusion@0.2.0"
Fusion-Components = "virtualbutfake/fusion-components@0.1.12"
ProfileService = "brittonfischer/profileservice@2.1.5"
Component = "sleitnick/component@2.4.8"