[package]
name = "sigmathetatech/sigmatech-luau-project-base"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

# Loader + TypedRemote will take place of Knit
[dependencies]
Loader = "sleitnick/loader@2.0.0"
TypedRemote = "sleitnick/typed-remote@0.2.0"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.1"
Janitor = "howmanysmall/janitor@1.16.0"
Component = "sleitnick/component@2.4.8"
React = "jsdotlua/react@17.2.1"
Ripple = "littensy/ripple@0.9.2"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"