[package]
name = "sigmathetatech/sigmatech-luau-project-base"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "0.1.0"

# Loader + TypedRemote will take place of Knit
[dependencies]
Component = "sleitnick/component@2.4.8"
Fusion = "elttob/fusion@0.2.0"
Fusion-Components = "virtualbutfake/fusion-components@0.1.12"
Janitor = "howmanysmall/janitor@1.16.0"
Loader = "sleitnick/loader@2.0.0"
ProfileService = "brittonfischer/profileservice@2.1.5"
Promise = "evaera/promise@4.0.0"
React = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
Roact-Spring = "chriscerie/roact-spring@2.0.0"
Signal = "sleitnick/signal@2.0.1"
TypedRemote = "sleitnick/typed-remote@0.2.0"
